server:
  port: 8081
  GIN_MODE: debug # debug, release, test

log:
  level: info

mysql:
  host: 127.0.0.1
  port: 3307
  user: root
  password: root
  database: bk_kms


jwt:
  secret: secretssssiwmiiu227m2
  exp: 1h